openapi: "3.0.3"

info:
  version: 1.0.3
  title: Initiate payment
  description: |
    This API allows users to trigger an HMRC payment journey from their software. 
    
    The workflow enables an API user to redirect a customer through to an HMRC payment journey. 
    If an optional back-url was provided by the API user we will offer this as a link to the customer to continue their journey.
    
    Additional details about the outcome of the payment can be discovered 
    by the API user by taking advantage of the /status endpoint.

    Typical lifetimes for journey storage are not yet determined.
    
    <div class="govuk-warning-text warning-icon-fix">
      <span class="govuk-warning-text__icon warning-icon-ui-fix" aria-hidden="true">!</span>
      <strong class="govuk-warning-text__text">
        <span class="govuk-warning-text__assistive">Warning</span>
        During this period if you wish to develop to this API please register your interest with SDST. We will update this page as soon as the API is available for general use.
      </strong>
    </div>

servers:
  - url: https://test-api.service.hmrc.gov.uk/payments/make-payment
    description: Sandbox
  - url: https://api.service.hmrc.gov.uk/payments/make-payment
    description: Production

components:
  securitySchemes:
    userRestricted:
      type: oauth2
      description: |
        HMRC supports OAuth 2.0 for authenticating user restricted API requests using an OAuth 2.0 Bearer Token in the AUTHORIZATION header.
        See https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints for details.
      flows:
        authorizationCode:
          authorizationUrl: https://api.service.hmrc.gov.uk/oauth/authorize
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          refreshUrl: https://api.service.hmrc.gov.uk/oauth/refresh
          scopes:
            status: Update the status of fraud check
    applicationRestricted:
      type: oauth2
      description: |
        HMRC supports OAuth 2.0 for authenticating application restricted API requests using an OAuth 2.0 Bearer Token in the AUTHORIZATION header.
        See https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/application-restricted-endpoints for details.
      flows:
        clientCredentials:
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          scopes: { }
  parameters:
    acceptHeader:
      name: Accept
      in: header
      schema:
        type: string
        enum: [ "application/vnd.hmrc.1.0+json" ]
      required: true
    contentTypeJsonHeader:
      name: "Content-Type"
      in: header
      description: |
        Specifies the format of the request body, which must be JSON.
      schema:
        type: string
        enum:
          - "application/json"
      required: true
    authorizationHeader:
      name: "Authorization"
      in: header
      description: |
        An OAuth 2.0 Bearer Token.
      schema:
        type: string
        example: Bearer bb7fed3fe10dd235a2ccda3d50fb
      required: true

paths:
  /pay:
    post:
      summary: Begin a payment journey.
      description: |
        After a successful call to the /pay endpoint, the API user receives JSON with a redirection URL. The API user
        then redirects the customer's browser to this URL, starting the payment journey.

      security:
        - applicationRestricted: [ ]
      requestBody:
        description: |
          The request body always contains the fields that allow HMRC to identify the liability that is being paid, so 
          that the funds are not mis-allocated. The required fields are the taxRegime, the reference and amountInPence.
          The backURL is an optional field containing a url to return the user to after they finish their payment.
          The friendlyName is an optional field to let the user know where they are being returned to after they finish their payment.
          If a field is labeled as optional, we intend this to mean that it should be *omitted entirely* - not sent through with a null value etc.
        required: true
        content:
          application/json:
            schema:
              title: Pay request schema
              description: The JSON describing an HMRC third party payment /pay payload.
              type: object
              required: [ taxRegime, reference, amountInPence ]
              properties:
                taxRegime:
                  type: string
                  description: |
                    The tax regime under which the liability has arisen. One of a fixed set. Currently supported regimes are: Self Assessment and Vat.
                  enum: [ SelfAssessment, Vat ]
                  example: SelfAssessment
                reference:
                  description: The reference identifying the tax liability. For Self Assessment this is the 10 digit Unique Taxpayer Reference. For VAT this is the 9-digit VAT registration number.
                  type: string
                  example: "1097172564"
                amountInPence:
                  description: The amount to be paid in pence, so Â£12.34 is 1234, must be greater than or equal to 0. If 0 is provided, the user will be prompted to enter an amount. If non zero is provided, the user will be prompted to select the amount or enter another amount.
                  type: integer
                  minimum: 0
                  exclusiveMinimum: false
                  example: 1234
                backURL:
                  description: If this is present HMRC will offer this as a link to the customer at the end of the journey, this link can allow them to return to their software.
                  type: string
                  format: uri
                  example: "https://some-accounting-software.com/after-pay/a218f71d9bf2438e851c71d50866c2e9"
                friendlyName:
                  description: The name of the software that the user started their payment from. If this is present, then we will display a link to help users go back to their software which says "return to &lt;friendlyName&gt;"
                  type: string
                  example: "Accounting Software Company X"

      responses:
        201:
          description: Created. Body contains url to redirect user to and a UUID to look up the status of the payment journey with.
          content:
            application/json:
              schema:
                type: object
                properties:
                  redirectURL:
                    type: string
                    description: The URL to direct the customer browser to in order to initiate the customer payment journey
                  clientJourneyId:
                    type: string
                    format: uuid
                    description: The client identifier created by HMRC for this journey. This will be a UUID (version 4, variant 2). This field is used to identify the journey in calls to the /status endpoint.
              example:
                {
                  "redirectURL": "https://tax.gov.uk/payments/start/jhdugiuygdwuygsxajvbh",
                  "clientJourneyId": "a218f71d-9bf2-438e-851c-71d50866c2e9"
                }

        400:
          description: |
            Bad Request.
            
            A 400 response represents a malformed request. The returned JSON will attempt to guide
            the API user to the problem.
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    description: The array contains the list of error messages.
                    items:
                      type: string
              example:
                { "errors": ["Mandatory reference field was omitted."] }

        500:
          description: An error occurred upstream and could not be recovered from.
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    description: The array contains the list of error messages.
                    items:
                      type: string
              example:
                { "errors": ["Error from upstream"] }

  /status:
    get:
      summary: Discover the status of a payment.
      description: |
        The API user can check the payment status by providing the clientJourneyId used 
        when the payment journey was created.
        The JSON body returned will include the clientJourneyId, the taxRegime, the amountInPence paid and also the paymentStatus.

        ### Test data
        Scenario simulation using Gov-Test-Scenario headers is *only available in the sandbox environment*.
        You will not be able to access the frontend screens to complete the journey, but you can use headers in the POST request 
        to set a journey into a certain state. To achieve this send a Gov-Test-Scenario header with a value matching one of the values below. 

        | Header Value (Gov-Test-Scenario) | Scenario description                                        |
        | -------------------------------- | ----------------------------------------------------------- |
        | COMPLETED                        | The payment has completed and the transfer is made.         |
        | FAILED                           | The payment has failed for one of the following reasons: <br> - The payment was cancelled by the user or timed out at the bank during the payment process. <br> - The bank or building society has rejected the payment. <br> - The payment has failed due to an error. |
        | IN_PROGRESS                      | The payment is in progress but has not completed or failed. |

      security:
        - applicationRestricted: [ ]

      parameters:
        - in: query
          name: clientJourneyId
          required: true
          description: The identifier for the payment journey.
          schema:
            type: string
            format: uuid
            example: "a218f71d-9bf2-438e-851c-71d50866c2e9"

      responses:
        200:
          description: |
            A payment matching the query was found and the details returned in the JSON response
          content:
            application/json:
              schema:
                type: object
                required: [ clientJourneyId, taxRegime, amountInPence, paymentStatus ]
                properties:
                  clientJourneyId:
                    type: string
                    description: The identifier for the payment journey.
                    example: "a218f71d-9bf2-438e-851c-71d50866c2e9"
                  taxRegime:
                    type: string
                    description: The tax regime under which the liability has arisen. One of a fixed set.
                    enum: [ SelfAssessment, Vat ]
                    example: "SelfAssessment"
                  amountInPence:
                    description: Represents the amount actually paid, in pence.
                    type: integer
                    example: 3456
                  paymentStatus:
                    description: |
                      The status of the payment within the HMRC system.
                    type: string
                    enum: [ Completed, Failed, InProgress ]
                    example: "Completed"
              example:
                {
                  "clientJourneyId": "a218f71d-9bf2-438e-851c-71d50866c2e9",
                  "taxRegime": "SelfAssessment",
                  "amountInPence": 1453,
                  "paymentStatus": "Completed"
                }
        400:
          description: |
            A malformed request. The returned JSON will attempt to guide
            the API user to the problem.

          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: |
                      An error containing what may be wrong with the request.
              example:
                { "error": "Mandatory clientJourneyId field of query was omitted." }
        404:
          description: |
            Either the payment journey never existed, or HMRC no longer has a record of the journey.
